"""empty message

Revision ID: 2236116646ff
Revises: 
Create Date: 2021-01-31 16:52:59.441593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2236116646ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type')
    op.drop_table('section')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='section_pkey'),
    sa.UniqueConstraint('section', name='section_section_key')
    )
    op.create_table('type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='type_pkey')
    )
    # ### end Alembic commands ###
